# Generated by Django 2.1 on 2018-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180903_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
