# Generated by Django 2.1 on 2018-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmodel_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='done',
            field=models.BooleanField(default=0),
        ),
    ]
