# Generated by Django 2.1 on 2018-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180903_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='text',
            field=models.TextField(max_length=256),
        ),
    ]
