# Generated by Django 2.1 on 2018-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('main_image', models.URLField(max_length=256)),
                ('second_image', models.URLField(max_length=256)),
                ('third_image', models.URLField(max_length=256)),
                ('short_description', models.TextField(max_length=256)),
                ('description', models.TextField(max_length=1024)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
    ]
