# Generated by Django 2.1 on 2018-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
