# Generated by Django 2.1 on 2018-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realizations', '0003_auto_20180904_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realization',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='realization',
            name='link',
        ),
        migrations.AddField(
            model_name='realization',
            name='second_image',
            field=models.URLField(default='www.google.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realization',
            name='short_description',
            field=models.TextField(default='dasdasD', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realization',
            name='third_image',
            field=models.URLField(default='www.google.com', max_length=256),
            preserve_default=False,
        ),
    ]
