# Generated by Django 2.1 on 2018-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='short_description',
            field=models.TextField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='description',
            field=models.TextField(max_length=2048),
        ),
    ]
